-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local primary = "rgb(7cda9b)"
local surface = "rgb(131313)"
local secondary = "rgb(b6ccb9)"
local error = "rgb(ffb4ab)"
local tertiary = "rgb(a2ceda)"
local surface_lowest = "rgb(0e0e0e)"

hl.config({
    general = {
        col = {
            active_border = primary,
            inactive_border = surface,
        },
    },
    group = {
        col = {
            border_active = secondary,
            border_inactive = surface,
            border_locked_active = error,
            border_locked_inactive = surface,
        },
        groupbar = {
            col = {
                active = secondary,
                inactive = surface,
                locked_active = error,
                locked_inactive = surface,
            },
        },
    },
})

