#wallpaper {
#    monitor = DP-3
#    path = ~/Pictures/wallpapers/redHexagons.png
#    fit_mode = cover
#}

wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/wallpapers/warrior.jpg
    fit_mode = fill
}

splash = false
#wallpaper {
#    monitor = DP-3
#    path = ~/Pictures/wallpapers/CherryBlossomAnimated.mp4
#    fit_mode = contain
#}
