# BACKGROUND
background {
    monitor =
    path = $HOME/.config/hypr/wallpapers/warrior.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    hide_cursor = true
    ignore_empty_input = true
}

# Backdrop shape behind all text/input
#shape {
#    monitor =
#    size = 420, 420
#    color = rgba(13, 0, 0, 0.55)
#    rounding = 12
#    border_size = 2
#    border_color = rgba(204, 34, 34, 0.6)
#    blur_passes = 3
#    blur_size = 7
#    position = 32, -140
#    halign = center
#    valign = center
#    zindex = 0
#}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span weight='bold'>$(date +"%I:%M")</span>"
    color = rgba(211, 198, 170, 0.95)
    font_size = 60
    font_family = JetBrainsMono Nerd Font
    position = 30, -8
    halign = center
    valign = center
    zindex = 1
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "<span weight='bold'>$(date +"%A, %B %d")</span>"
    color = rgba(157, 169, 160, 0.85)
    font_size = 19
    font_family = JetBrainsMono Nerd Font
    position = 35, -60
    halign = center
    valign = center
    zindex = 1
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    rounding = 6

    outer_color = rgba(167, 192, 128, 0.9)
    inner_color = rgba(45, 53, 59, 0.85)
    font_color = rgb(211, 198, 170)

    check_color = rgba(167, 192, 128, 1.0) rgba(131, 192, 146, 1.0) 45deg
    fail_color = rgba(230, 126, 128, 1.0) rgba(176, 93, 98, 1.0) 40deg
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = rgba(219, 188, 127, 1.0)

    fade_on_empty = true
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##d3c6aa99">🔒</span></i>
    hide_input = false

    position = 34, -268
    halign = center
    valign = center
    zindex = 1
}

