# ~/.config/hypr/hyprtoolkit.conf

background     = 0xFF0d0000
base           = 0xFF1a0000
alternate_base = 0xFF220000
text           = 0xFFe8d0d0
bright_text    = 0xFFffffff

accent         = 0xFFcc2222
accent_secondary = 0xFF8b0000

h1_size        = 19
h2_size        = 15
h3_size        = 13
font_size      = 11
small_font_size = 10
