-- Monitors
-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-3",
    mode = "5120x1440@119.97",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100",
    position = "640x-1080",
    scale = "1",
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@100",
    position = "2560x-1080",
    scale = "1",
})

-- Pin workspaces to monitors so the ultrawide gets WS1 regardless of init order.
hl.workspace_rule({
    workspace = "1",
    monitor = "DP-3",
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-2",
    default = true,
    persistent = true,
})

