-- Window & workspace rules

-- --- Global hygiene ---
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- --- Smart gaps: remove borders/rounding when only 1 tiled window or fullscreen ---
hl.window_rule({
    name = "no-borders-single",
    match = {
        float = false,
        workspace = "w[tv1]",
    },
    border_size = 0,
    rounding = 0,
})

hl.window_rule({
    name = "no-borders-fullscreen",
    match = {
        float = false,
        workspace = "f[1]",
    },
    border_size = 0,
    rounding = 0,
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- --- Hyprland-run floating dock ---
hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

-- --- cmatrix screensaver ---
hl.window_rule({
    name = "cmatrix-bg",
    match = {
        class = "kittyscreensaver",
    },
    fullscreen = true,
    idle_inhibit = "none",
})

-- --- Kitty: no blur (terminals read better crisp, saves GPU) ---
hl.window_rule({
    name = "kitty-noblur",
    match = {
        class = "^(kitty)$",
    },
    no_blur = true,
})

hl.window_rule({
    name = "kitty-drop-noblur",
    match = {
        class = "^(kitty-drop)$",
    },
    no_blur = true,
})

-- --- Scratchpad windows (all share special:magic, toggled with SUPER+S) ---
-- NOTE: initial workspace placement for browser/discord/telegram/kitty is done
-- via [workspace N silent] prefixes in 30-autostart.conf, NOT persistent
-- windowrules. This way manually-launched windows open on the current
-- workspace, not the autostart target.

hl.window_rule({
    name = "kitty-drop-scratch",
    match = {
        class = "^(kitty-drop)$",
    },
    float = true,
    size = "70% 55%",
    center = true,
    workspace = "special:magic silent",
})

hl.window_rule({
    name = "mousepad-scratch",
    match = {
        class = "^([Mm]ousepad)$",
    },
    float = true,
    size = "70% 70%",
    center = true,
    workspace = "special:magic silent",
})

