color0 #131313
color1 #ffb4ab
color2 #7cda9b
color3 #b6ccb9
color4 #a2ceda
color5 #7cda9b
color6 #b6ccb9
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #7cda9b
color11 #b6ccb9
color12 #a2ceda
color13 #7cda9b
color14 #b6ccb9
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #7cda9b
inactive_border_color #474747
url_color             #7cda9b

active_tab_foreground   #00391c
active_tab_background   #7cda9b
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
